apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-bridge
  namespace: black-friday
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-bridge
  template:
    metadata:
      labels:
        app: go-bridge
    spec:
      containers:
      - name: go-bridge
        image: ttl.sh/go-bridge-202300539:2h
        ports:
        - containerPort: 8080
        env:
        - name: GRPC_HOST
          value: "go-writer-service:50051" # Conecta con el Writer existente
---
apiVersion: v1
kind: Service
metadata:
  name: go-bridge-service
  namespace: black-friday
spec:
  type: ClusterIP
  selector:
    app: go-bridge
  ports:
    - protocol: TCP
      port: 80         # Puerto interno del cluster
      targetPort: 8080 # Puerto de tu contenedor