apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-writer
  namespace: black-friday
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-writer
  template:
    metadata:
      labels:
        app: go-writer
    spec:
      containers:
      - name: go-writer
        image: 172.31.13.124:5000/go-writer:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        env:
        - name: KAFKA_BROKERS
          value: "my-cluster-kafka-bootstrap.kafka.svc:9092"
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: go-writer-service
  namespace: black-friday
spec:
  type: ClusterIP
  selector:
    app: go-writer
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051